server:
  port : 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
      show-sql: true